services:
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    restart: always
    ports:
      - "3005:80"
    environment:
      - VITE_API_URL=http://api:7500
    depends_on:
      - api
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    ports:
      - "7500:7500"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/shop
      - ADMIN_KEY=${ADMIN_KEY}
    networks:
      - app_network

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:7500
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    external: true